import { Festival, FestivalStyle, Language } from './types';

export const FESTIVALS: Festival[] = [
  {
    id: 'lny-reunion',
    nameEn: 'Reunion Dinner',
    nameZh: '年三十晚團年飯',
    nameSc: '年三十晚团年饭',
    nameJa: '大晦日の団らん夕食',
    nameKo: '섣달 그믐날 재회 만찬',
    nameDe: 'Wiedersehens-Abendessen',
    dateEn: 'LNY Eve',
    dateZh: '農曆年三十',
    dateSc: '农历年三十',
    dateJa: '旧正月の大晦日',
    dateKo: '설날 전날',
    dateDe: 'LNY Vorabend',
    greetingEn: 'Happy Reunion Dinner',
    greetingZh: '團團圓圓，歲歲平安',
    greetingSc: '团团圆圆，岁岁平安',
    greetingJa: '団らんのひとときを',
    greetingKo: '즐거운 재회 만찬 되세요',
    greetingDe: 'Frohes Wiedersehens-Abendessen',
    icon: '🍲',
    basePrompt: 'Chinese Lunar New Year Eve Reunion. A large round table overflowing with traditional feast dishes: steamed fish, dumplings, abalone. Warm golden indoor lighting, family atmosphere, red lanterns in background.'
  },
  {
    id: 'lny-day1',
    nameEn: 'Lunar New Year',
    nameZh: '農曆新年',
    nameSc: '春节',
    nameJa: '旧正月',
    nameKo: '설날',
    nameDe: 'Mondneujahr',
    dateEn: 'Day 1-3',
    dateZh: '農曆正月初一',
    dateSc: '农历正月初一',
    dateJa: '旧正月1日目',
    dateKo: '설날 첫날',
    dateDe: 'Tag 1-3',
    greetingEn: 'Happy Lunar New Year',
    greetingZh: '恭喜發財，大吉大利',
    greetingSc: '恭喜发财，大吉大利',
    greetingJa: '新年あけましておめでとう',
    greetingKo: '새해 복 많이 받으세요',
    greetingDe: 'Frohes Mondneujahr',
    icon: '🧧',
    basePrompt: 'Traditional Lunar New Year celebration. Vibrant red and gold decorations, plum blossoms (Meihua), firecracker ornaments, red envelopes everywhere, joyous and bright atmosphere.'
  },
  {
    id: 'lny-renri',
    nameEn: "Everyone's Birthday",
    nameZh: '正月初七人日',
    nameSc: '正月初七人日',
    nameJa: '人の日',
    nameKo: '인일 (사람의 날)',
    nameDe: 'Tag der Menschen',
    dateEn: 'Day 7 (Renri)',
    dateZh: '農曆正月初七',
    dateSc: '农历正月初七',
    dateJa: '旧正月7日目',
    dateKo: '설날 7일째',
    dateDe: 'Tag 7 (Renri)',
    greetingEn: "Happy Human's Day",
    greetingZh: '人日快樂，龍馬精神',
    greetingSc: '人日快乐，龙马精神',
    greetingJa: '人の日おめでとう',
    greetingKo: '인일 축하합니다',
    greetingDe: 'Alles Gute zum Tag der Menschen',
    icon: '🥗',
    basePrompt: 'Chinese Renri festival celebration. People performing "Lo Hei" (prosperity toss) with a colorful Yusheng salad. Joyful atmosphere, spring garden setting, symbols of longevity and health.'
  },
  {
    id: 'lny-lantern',
    nameEn: 'Lantern Festival',
    nameZh: '元宵節',
    nameSc: '元宵节',
    nameJa: '元宵節',
    nameKo: '원소절',
    nameDe: 'Laternenfest',
    dateEn: 'Day 15',
    dateZh: '農曆正月十五',
    dateSc: '农历正月十五',
    dateJa: '旧正月15日目',
    dateKo: '설날 15일째',
    dateDe: 'Tag 15',
    greetingEn: 'Happy Lantern Festival',
    greetingZh: '元宵節快樂，月圓人團圓',
    greetingSc: '元宵节快乐，月圆人团圆',
    greetingJa: '元宵節おめでとう',
    greetingKo: '즐거운 원소절 되세요',
    greetingDe: 'Frohes Laternenfest',
    icon: '🏮',
    basePrompt: 'Chinese Lantern Festival at night. Hundreds of glowing red paper lanterns floating in the sky and hanging from trees. A large bright full moon, romantic and peaceful night atmosphere, reflections in water.'
  },
  {
    id: 'white-valentine',
    nameEn: 'White Valentine',
    nameZh: '白色情人節',
    nameSc: '白色情人节',
    nameJa: 'ホワイトデー',
    nameKo: '화이트데이',
    nameDe: 'Weißer Valentinstag',
    dateEn: 'Mar 14th',
    dateZh: '3月14日',
    dateSc: '3月14日',
    dateJa: '3月14日',
    dateKo: '3월 14일',
    dateDe: '14. März',
    greetingEn: 'Pure Love & Sweetness',
    greetingZh: '白色驚喜，愛在心裡',
    greetingSc: '白色惊喜，爱在心里',
    greetingJa: '純粋な愛を込めて',
    greetingKo: '순수한 사랑과 달콤함',
    greetingDe: 'Reine Liebe & Süße',
    icon: '🤍',
    basePrompt: 'White Valentine\'s Day theme. Elegant white decor, white chocolate treats, soft minimalist aesthetics, high-end white floral arrangements, gentle morning light.'
  },
  {
    id: 'diwali',
    nameEn: 'Diwali',
    nameZh: '排燈節',
    nameSc: '排灯节',
    nameJa: 'ディワリ',
    nameKo: '디왈리',
    nameDe: 'Diwali',
    dateEn: 'Oct - Nov',
    dateZh: '10月 - 11月',
    dateSc: '10月 - 11月',
    dateJa: '10月 - 11月',
    dateKo: '10월 - 11월',
    dateDe: 'Okt - Nov',
    greetingEn: 'Happy Diwali!',
    greetingZh: '排燈節快樂，光明驅散黑暗',
    greetingSc: '排灯节快乐，光明驱散黑暗',
    greetingJa: 'ディワリおめでとう',
    greetingKo: '행복한 디왈리 되세요',
    greetingDe: 'Frohes Diwali!',
    icon: '🪔',
    basePrompt: 'Vibrant Diwali celebration (Festival of Lights). Thousands of glowing Diya lamps, colorful Rangoli floor art, sparkling fireworks in the night sky, warm orange and gold hues.'
  },
  {
    id: 'new-year',
    nameEn: 'New Year Day',
    nameZh: '元旦新年',
    nameSc: '元旦新年',
    nameJa: '元旦',
    nameKo: '새해 첫날',
    nameDe: 'Neujahrstag',
    dateEn: 'Jan 1st',
    dateZh: '1月1日',
    dateSc: '1月1日',
    dateJa: '1月1日',
    dateKo: '1월 1일',
    dateDe: '1. Januar',
    greetingEn: 'Happy New Year!',
    greetingZh: '新年快樂，萬象更新',
    greetingSc: '新年快乐，万象更新',
    greetingJa: 'あけましておめでとう',
    greetingKo: '새해 복 많이 받으세요',
    greetingDe: 'Frohes neues Jahr!',
    icon: '🎊',
    basePrompt: 'Global New Year celebration. Fireworks exploding over a modern city skyline, confetti falling, champagne toasts, bright blue and silver festive lighting.'
  },
  {
    id: 'thanksgiving',
    nameEn: 'Thanksgiving',
    nameZh: '感恩節',
    nameSc: '感恩节',
    nameJa: '感謝祭',
    nameKo: '추석 (추수감사절)',
    nameDe: 'Erntedankfest',
    dateEn: 'Nov 4th Thu',
    dateZh: '11月第四個週四',
    dateSc: '11月第四个周四',
    dateJa: '11月第4木曜日',
    dateKo: '11월 넷째 목요일',
    dateDe: '4. Do im Nov',
    greetingEn: 'Happy Thanksgiving!',
    greetingZh: '感恩有你，歲月靜好',
    greetingSc: '感恩有你，岁月静好',
    greetingJa: '感謝祭おめでとう',
    greetingKo: '행복한 추수감사절 되세요',
    greetingDe: 'Frohes Erntedankfest!',
    icon: '🦃',
    basePrompt: 'Thanksgiving harvest feast. A golden roasted turkey center-piece, pumpkins, autumn leaves, warm rustic wooden dining room, cozy candlelight, cornucopia of vegetables.'
  },
  {
    id: 'black-friday',
    nameEn: 'Black Friday',
    nameZh: '黑色星期五',
    nameSc: '黑色星期五',
    nameJa: 'ブラックフライデー',
    nameKo: '블랙 프라이데이',
    nameDe: 'Black Friday',
    dateEn: 'Nov Fri',
    dateZh: '11月週五',
    dateSc: '11月周五',
    dateJa: '11月の金曜日',
    dateKo: '11월 금요일',
    dateDe: 'Fr im Nov',
    greetingEn: 'Best Deals Ever!',
    greetingZh: '狂歡購物，折上折',
    greetingSc: '狂欢购物，折上折',
    greetingJa: '最高のセールを！',
    greetingKo: '최고의 딜을 만나보세요!',
    greetingDe: 'Beste Angebote aller Zeiten!',
    icon: '🛍️',
    basePrompt: 'High-energy Black Friday shopping atmosphere. Neon "SALE" signs, futuristic retail environment, stylish shopping bags, sleek dark aesthetic with vibrant magenta and cyan accents.'
  },
  {
    id: 'beer-fest',
    nameEn: 'Beer Festival',
    nameZh: '啤酒節',
    nameSc: '啤酒节',
    nameJa: 'ビール祭り',
    nameKo: '맥주 축제',
    nameDe: 'Bierfest',
    dateEn: 'Oct',
    dateZh: '10月',
    dateSc: '10月',
    dateJa: '10月',
    dateKo: '10월',
    dateDe: 'Okt',
    greetingEn: 'Prost! Cheers!',
    greetingZh: '盡情乾杯，歡度節慶',
    greetingSc: '尽情干杯，欢度节庆',
    greetingJa: '乾杯！',
    greetingKo: '건배! 축제를 즐기세요!',
    greetingDe: 'Prost! Zum Wohl!',
    icon: '🍺',
    basePrompt: 'Bavarian Oktoberfest celebration. Huge frothy beer steins, traditional wooden beer hall, blue and white checkered banners, lively communal atmosphere, pretzels and bratwurst.'
  },
  {
    id: 'hanami',
    nameEn: 'Hanami (Cherry Blossom)',
    nameZh: '櫻花祭',
    nameSc: '樱花祭',
    nameJa: '花見',
    nameKo: '하나미 (벚꽃 축제)',
    nameDe: 'Hanami (Kirschblüte)',
    dateEn: 'Spring',
    dateZh: '春季',
    dateSc: '春季',
    dateJa: '春',
    dateKo: '봄',
    dateDe: 'Frühling',
    greetingEn: 'Spring is here!',
    greetingZh: '櫻花盛開，春意盎然',
    greetingSc: '樱花盛开，春意盎然',
    greetingJa: '春が来ました！',
    greetingKo: '봄이 왔어요!',
    greetingDe: 'Der Frühling ist da!',
    icon: '🌸',
    basePrompt: 'Japanese Sakura Hanami festival. Thousands of blooming cherry blossom trees, falling pink petals, traditional Japanese park with a red bridge, Mount Fuji in the distant background, soft ethereal lighting.'
  },
  {
    id: 'songkran',
    nameEn: 'Songkran',
    nameZh: '潑水節',
    nameSc: '泼水节',
    nameJa: 'ソンクラーン',
    nameKo: '송크란',
    nameDe: 'Songkran',
    dateEn: 'Apr 13-15',
    dateZh: '4月13-15日',
    dateSc: '4月13-15日',
    dateJa: '4月13-15日',
    dateKo: '4월 13-15일',
    dateDe: '13.-15. Apr',
    greetingEn: 'Happy Songkran!',
    greetingZh: '潑水迎新，清涼平安',
    greetingSc: '泼水迎新，清凉平安',
    greetingJa: 'ソンクラーンおめでとう',
    greetingKo: '행복한 송크란 되세요!',
    greetingDe: 'Frohes Songkran!',
    icon: '💦',
    basePrompt: 'Thai Songkran Water Festival. Sunny tropical street, people splashing water with buckets and water guns, joyous expressions, traditional Thai temple architecture in the background, colorful summer vibes.'
  },
  {
    id: 'dragon-boat',
    nameEn: 'Dragon Boat',
    nameZh: '端午節',
    nameSc: '端午节',
    nameJa: '端午の節句',
    nameKo: '단오제',
    nameDe: 'Drachenbootfest',
    dateEn: 'Lunar May 5',
    dateZh: '農曆五月初五',
    dateSc: '农历五月初五',
    dateJa: '旧暦5月5日',
    dateKo: '음력 5월 5일',
    dateDe: 'Mond-Mai 5',
    greetingEn: 'Ride the Dragon!',
    greetingZh: '端午安康，百舟競渡',
    greetingSc: '端午安康，百舟竞渡',
    greetingJa: '端午の節句おめでとう',
    greetingKo: '즐거운 단오제 되세요',
    greetingDe: 'Reite den Drachen!',
    icon: '🐲',
    basePrompt: 'Dragon Boat Festival racing on a wide river. Traditional colorful dragon boats with rowers, rhythmic drumming, splashes of water, Zongzi (sticky rice dumplings) in foreground, green bamboo leaves decoration.'
  },
  {
    id: 'st-george',
    nameEn: 'St. George\'s Day',
    nameZh: '聖喬治日',
    nameSc: '圣乔治日',
    nameJa: '聖ジョージの日',
    nameKo: '성 조지의 날',
    nameDe: 'St. Georgstag',
    dateEn: 'Apr 23',
    dateZh: '4月23日',
    dateSc: '4月23日',
    dateJa: '4月23日',
    dateKo: '4월 23일',
    dateDe: '23. April',
    greetingEn: 'Courage & Honor!',
    greetingZh: '英勇榮耀，傳統慶典',
    greetingSc: '英勇荣耀，传统庆典',
    greetingJa: '勇気と名誉を！',
    greetingKo: '용기와 명예!',
    greetingDe: 'Mut & Ehre!',
    icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    basePrompt: 'St. George\'s Day celebration. English Red Cross flags fluttering, medieval castle backdrop, stylized silver dragon motifs, red roses, chivalrous and historic English countryside atmosphere.'
  },
  {
    id: 'easter',
    nameEn: 'Easter',
    nameZh: '復活節',
    nameSc: '复活节',
    nameJa: 'イースター',
    nameKo: '부활절',
    nameDe: 'Ostern',
    dateEn: 'Spring',
    dateZh: '春季',
    dateSc: '春季',
    dateJa: '春',
    dateKo: '봄',
    dateDe: 'Frühling',
    greetingEn: 'Happy Easter!',
    greetingZh: '復活節快樂，萬象更新',
    greetingSc: '复活节快乐，万象更新',
    greetingJa: 'イースターおめでとう',
    greetingKo: '행복한 부활절 되세요',
    greetingDe: 'Frohe Ostern!',
    icon: '🐰',
    basePrompt: 'Easter morning in a lush green meadow. Colorful hand-painted eggs hidden in long grass, cute bunnies, blooming daffodils and tulips, soft morning sunlight, bright and cheerful spring colors.'
  },
  {
    id: 'british-garden',
    nameEn: 'British Garden Party',
    nameZh: '英式庭園派對',
    nameSc: '英式庭园派对',
    nameJa: '英国式ガーデンパーティー',
    nameKo: '영국식 가든 파티',
    nameDe: 'Britische Gartenparty',
    dateEn: 'Summer',
    dateZh: '夏季',
    dateSc: '夏季',
    dateJa: '夏',
    dateKo: '여름',
    dateDe: 'Sommer',
    greetingEn: 'A Splendid Day!',
    greetingZh: '英式典雅，愜意時光',
    greetingSc: '英式典雅，惬意时光',
    greetingJa: '素敵な一日を！',
    greetingKo: '멋진 하루 되세요!',
    greetingDe: 'Ein herrlicher Tag!',
    icon: '🫖',
    basePrompt: 'Elegant British Summer Garden Party. Lush green manicured lawns, colorful bunting, floral arrangements. Subjects wearing fascinators or linen suits. High tea setup with scones and tiered cake stands.'
  },
  {
    id: 'pm-day',
    nameEn: 'Project Management Day',
    nameZh: '國際專案管理日',
    nameSc: '国际专案管理日',
    nameJa: '国際プロジェクトマネジメントの日',
    nameKo: '국제 프로젝트 관리의 날',
    nameDe: 'Projektmanagement-Tag',
    dateEn: 'Nov 1st',
    dateZh: '11月1日',
    dateSc: '11月1日',
    dateJa: '11月1日',
    dateKo: '11월 1일',
    dateDe: '1. November',
    greetingEn: 'On Time & On Budget!',
    greetingZh: '專案成功，效率至上',
    greetingSc: '专案成功，效率至上',
    greetingJa: '計画通り、予算通りに！',
    greetingKo: '정시 및 예산 내 성공!',
    greetingDe: 'Pünktlich & im Budget!',
    icon: '📊',
    basePrompt: 'International Project Management Day celebration. Modern corporate office success vibe. Glass boards with colorful Kanban stickies, Gantt charts on screens, professional and celebratory atmosphere, "Success" metrics visualization.'
  },
  {
    id: 'valentine',
    nameEn: "Valentine's Day",
    nameZh: '情人節',
    nameSc: '情人节',
    nameJa: 'バレンタインデー',
    nameKo: '발렌타인데이',
    nameDe: 'Valentinstag',
    dateEn: 'Feb 14th',
    dateZh: '2月14日',
    dateSc: '2月14日',
    dateJa: '2月14日',
    dateKo: '2월 14일',
    dateDe: '14. Februar',
    greetingEn: "Happy Valentine's Day",
    greetingZh: '情人節快樂',
    greetingSc: '情人节快乐',
    greetingJa: 'ハッピーバレンタイン',
    greetingKo: '행복한 발렌타인데이',
    greetingDe: 'Alles Gute zum Valentinstag',
    icon: '💝',
    basePrompt: 'Romantic Valentine\'s Day setting. Soft bokeh heart-shaped lights, rose petals, elegant candles, warm pink and red color palette.'
  },
  {
    id: 'mid-autumn',
    nameEn: 'Mid-Autumn',
    nameZh: '中秋節',
    nameSc: '中秋节',
    nameJa: '中秋の名月',
    nameKo: '추석',
    nameDe: 'Mondfest',
    dateEn: 'Sep - Oct',
    dateZh: '農曆八月十五',
    dateSc: '农历八月十五',
    dateJa: '旧暦8月15日',
    dateKo: '음력 8월 15일',
    dateDe: 'Sep - Okt',
    greetingEn: 'Happy Mid-Autumn',
    greetingZh: '中秋節快樂，千里共嬋娟',
    greetingSc: '中秋节快乐，千里共婵娟',
    greetingJa: '中秋の名月おめでとう',
    greetingKo: '즐거운 추석 되세요',
    greetingDe: 'Frohes Mondfest',
    icon: '🥮',
    basePrompt: 'Traditional Mid-Autumn festival. A massive glowing full moon, traditional Chinese architecture, osmanthus flowers, glowing rabbit lanterns.'
  },
  {
    id: 'christmas',
    nameEn: 'Christmas',
    nameZh: '聖誕節',
    nameSc: '圣诞节',
    nameJa: 'クリスマス',
    nameKo: '크리스마스',
    nameDe: 'Weihnachten',
    dateEn: 'Dec 25th',
    dateZh: '12月25日',
    dateSc: '12月25日',
    dateJa: '12月25日',
    dateKo: '12월 25일',
    dateDe: '25. Dezember',
    greetingEn: 'Merry Christmas',
    greetingZh: '聖誕快樂',
    greetingSc: '圣诞快乐',
    greetingJa: 'メリークリスマス',
    greetingKo: '메리 크리스마스',
    greetingDe: 'Frohe Weihnachten',
    icon: '🎄',
    basePrompt: 'Western Christmas celebration. A grand glowing Christmas tree, soft bokeh lights, cozy fireplace, falling snow outside the window.'
  }
];

export const STYLES: FestivalStyle[] = [
  { 
    id: 'cinematic', 
    nameEn: 'Cinematic', 
    nameZh: '電影寫實', 
    nameSc: '电影写实',
    nameJa: 'シネマティック',
    nameKo: '시네마틱',
    nameDe: 'Cinematic',
    thumbnailIcon: '🎬', 
    category: 'Realism', 
    prompt: 'Ultra-high-end cinematic realism. The subject must be seamlessly integrated into the festive environment with matching ambient lighting, realistic shadow casting, and unified color grading. Ensure the subject looks like they are physically part of the scene, not superimposed. High dynamic range, natural skin textures, and professional film-still quality.' 
  },
  { 
    id: 'hk-comic', 
    nameEn: 'HK Comic', 
    nameZh: '港式漫畫', 
    nameSc: '港式漫画',
    nameJa: '香港コミック',
    nameKo: '홍콩 만화',
    nameDe: 'HK Comic',
    thumbnailIcon: '👊', 
    category: 'Pop', 
    prompt: 'Traditional Hong Kong Manhua (HK Comic) style. Intense and detailed line art, muscular character anatomy, vibrant saturated colors, dramatic martial arts energy effects (Qi/Aura), expressive and fierce facial features, high-contrast digital painting style inspired by classic 90s martial arts manhua.' 
  },
  { 
    id: 'comic', 
    nameEn: 'American Comic', 
    nameZh: '美式漫畫', 
    nameSc: '美式漫画',
    nameJa: 'アメコミ',
    nameKo: '미국 만화',
    nameDe: 'Amerikanischer Comic',
    thumbnailIcon: '💥', 
    category: 'Pop', 
    prompt: 'Dynamic American superhero comic book art style. Bold black outlines, halftone dot textures (Ben-Day dots), high contrast shadows, action-oriented composition, vintage comic aesthetic.' 
  },
  { 
    id: 'ink', 
    nameEn: 'Ink Wash', 
    nameZh: '中式水墨', 
    nameSc: '中式水墨',
    nameJa: '水墨画',
    nameKo: '수묵화',
    nameDe: 'Tuschmalerei',
    thumbnailIcon: '🖌️', 
    category: 'Artistic', 
    prompt: 'Traditional Chinese Ink Wash Painting. Expressive black ink brushstrokes on rice paper with subtle color accents.' 
  },
  { 
    id: 'manga', 
    nameEn: 'Manga', 
    nameZh: '日本動漫', 
    nameSc: '日本动漫',
    nameJa: 'マンガ',
    nameKo: '만화',
    nameDe: 'Manga',
    thumbnailIcon: '🍱', 
    category: 'Pop', 
    prompt: 'Modern Japanese manga style. Vibrant colors, clean line art, expressive eyes.' 
  },
  { 
    id: 'oil', 
    nameEn: 'Oil Painting', 
    nameZh: '西式油畫', 
    nameSc: '西式油画',
    nameJa: '油絵',
    nameKo: '유화',
    nameDe: 'Ölgemälde',
    thumbnailIcon: '🖼️', 
    category: 'Artistic', 
    prompt: 'Classic Western Oil Painting. Thick impasto brushstrokes, rich textures, dramatic lighting.' 
  }
];

export const TRANSLATIONS = {
  [Language.EN]: {
    title: 'AI Festival Studio',
    subtitle: 'Crafting Digital Memories',
    uploadPrompt: 'Upload Selfie',
    changePhoto: 'Change Photo',
    selectFestival: 'Choose Occasion',
    selectStyle: 'Art Style',
    selectOrientation: 'Aspect Ratio',
    generateBtn: 'Create Masterpiece',
    generating: 'Painting Your Vision...',
    download: 'Save Card',
    restart: 'Create New',
    error: 'Generation failed. Try again.',
    switchLang: 'Language',
    vertical: 'Portrait',
    horizontal: 'Landscape',
    square: 'Square',
    petNotice: 'Include friends or pets!',
    customBackgroundHeader: 'Custom Scene (Optional)',
    backgroundTextLabel: 'Describe the world...',
    backgroundImageLabel: 'Reference image...',
    clearBackground: 'Clear',
    customGreetingHeader: 'Message Overlay',
    customGreetingPlaceholder: 'Type your message...',
    textStyleLabel: 'Typography',
    editMessage: 'Edit Text',
    saveNotice: 'Blending high-res art and text...'
  },
  [Language.ZH]: {
    title: 'AI 節日賀卡工坊',
    subtitle: '打造獨一無二的數位回憶',
    uploadPrompt: '上傳自拍',
    changePhoto: '更換照片',
    selectFestival: '選擇節日/場合',
    selectStyle: '藝術風格',
    selectOrientation: '畫幅比例',
    generateBtn: '開始創作',
    generating: 'AI 正在精雕細琢...',
    download: '下載賀卡',
    restart: '重新製作',
    error: '生成失敗，請再試一次。',
    switchLang: '語言',
    vertical: '直式',
    horizontal: '橫式',
    square: '正方形',
    petNotice: '歡迎家人與寵物入鏡！',
    customBackgroundHeader: '自定義場景 (選填)',
    backgroundTextLabel: '描述背景細節...',
    backgroundImageLabel: '參考圖...',
    clearBackground: '清除',
    customGreetingHeader: '自訂祝福語',
    customGreetingPlaceholder: '輸入您的祝福...',
    textStyleLabel: '文字樣式',
    editMessage: '編輯文字',
    saveNotice: '正在合成高清圖像與完美文字...'
  },
  [Language.SC]: {
    title: 'AI 节日贺卡工坊',
    subtitle: '打造独一无二的数字回忆',
    uploadPrompt: '上传自拍',
    changePhoto: '更换照片',
    selectFestival: '选择节日/场合',
    selectStyle: '艺术风格',
    selectOrientation: '画幅比例',
    generateBtn: '开始创作',
    generating: 'AI 正在精雕细琢...',
    download: '下载贺卡',
    restart: '重新制作',
    error: '生成失败，请再试一次。',
    switchLang: '语言',
    vertical: '直式',
    horizontal: '横式',
    square: '正方形',
    petNotice: '欢迎家人与宠物入镜！',
    customBackgroundHeader: '自定义场景 (选填)',
    backgroundTextLabel: '描述背景细节...',
    backgroundImageLabel: '参考图...',
    clearBackground: '清除',
    customGreetingHeader: '自订祝福语',
    customGreetingPlaceholder: '输入您的祝福...',
    textStyleLabel: '文字样式',
    editMessage: '编辑文字',
    saveNotice: '正在合成高清图像 with 完美文字...'
  },
  [Language.JA]: {
    title: 'AIフェスティバルスタジオ',
    subtitle: 'デジタルの思い出を作る',
    uploadPrompt: '自撮りをアップロード',
    changePhoto: '写真を変更',
    selectFestival: '行事を選択',
    selectStyle: 'アートスタイル',
    selectOrientation: 'アスペクト比',
    generateBtn: '傑作を作成',
    generating: 'ビジョンを描いています...',
    download: 'カードを保存',
    restart: '新しく作成',
    error: '生成に失敗しました。もう一度お試しください。',
    switchLang: '言語',
    vertical: 'ポートレート',
    horizontal: 'ランドスケープ',
    square: 'スクエア',
    petNotice: '友達やペットも一緒に！',
    customBackgroundHeader: 'カスタムシーン（オプション）',
    backgroundTextLabel: '世界を表現する...',
    backgroundImageLabel: '参考画像...',
    clearBackground: 'クリア',
    customGreetingHeader: 'メッセージオーバーレイ',
    customGreetingPlaceholder: 'メッセージを入力...',
    textStyleLabel: 'タイ포그래피',
    editMessage: 'テキストを編集',
    saveNotice: '高解像度のアートとテキストをブレンド中...'
  },
  [Language.KO]: {
    title: 'AI 페스티벌 스튜디오',
    subtitle: '디지털 추억 만들기',
    uploadPrompt: '셀카 업로드',
    changePhoto: '사진 변경',
    selectFestival: '행사 선택',
    selectStyle: '아트 스타일',
    selectOrientation: '가로세로 비율',
    generateBtn: '걸작 만들기',
    generating: '비전을 그리는 중...',
    download: '카드 저장',
    restart: '새로 만들기',
    error: '생성에 실패했습니다. 다시 시도해 주세요.',
    switchLang: '언어',
    vertical: '세로',
    horizontal: '가로',
    square: '정사각형',
    petNotice: '친구 나 애완 동물을 포함하십시오!',
    customBackgroundHeader: '커스텀 배경 (선택 사항)',
    backgroundTextLabel: '세상을 묘사하세요...',
    backgroundImageLabel: '참조 이미지...',
    clearBackground: '지우기',
    customGreetingHeader: '메시지 오버레이',
    customGreetingPlaceholder: '메시지를 입력하세요...',
    textStyleLabel: '타이포그래피',
    editMessage: '텍스트 편집',
    saveNotice: '고해상도 아트와 텍스트 혼합 중...'
  },
  [Language.DE]: {
    title: 'AI Festival Studio',
    subtitle: 'Digitale Erinnerungen gestalten',
    uploadPrompt: 'Selfie hochladen',
    changePhoto: 'Foto ändern',
    selectFestival: 'Anlass wählen',
    selectStyle: 'Kunststil',
    selectOrientation: 'Seitenverhältnis',
    generateBtn: 'Meisterwerk erstellen',
    generating: 'Vision wird gemalt...',
    download: 'Karte speichern',
    restart: 'Neu erstellen',
    error: 'Generierung fehlgeschlagen. Erneut versuchen.',
    switchLang: 'Sprache',
    vertical: 'Porträt',
    horizontal: 'Landschaft',
    square: 'Quadrat',
    petNotice: 'Inklusive Freunde oder Haustiere!',
    customBackgroundHeader: 'Eigene Szene (Optional)',
    backgroundTextLabel: 'Beschreibe die Welt...',
    backgroundImageLabel: 'Referenzbild...',
    clearBackground: 'Löschen',
    customGreetingHeader: 'Nachricht Überlagerung',
    customGreetingPlaceholder: 'Nachricht eingeben...',
    textStyleLabel: 'Typografie',
    editMessage: 'Text bearbeiten',
    saveNotice: 'Mische hochauflösende Kunst und Text...'
  }
};
